---
- name: "Prepare"
  hosts: "all"
  become: True
  tasks:
    - name: "Prepare | Ensure required groups exist"
      ansible.builtin.group:
        name: "{{ item }}"
        state: "present"
      loop: "{{ users_create | selectattr('groups', 'defined') | map(attribute='groups') | flatten | unique | list }}"

    - name: "Prepare | Create users for deletion"
      ansible.builtin.user:
        name: "{{ item.name }}"
        create_home: True
        state: "present"
      loop: "{{ users_delete }}"
